# Generated by Django 5.2.1 on 2025-05-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('QR_CREATED', 'QR Code Created'), ('QR_UPDATED', 'QR Code Updated'), ('QR_DELETED', 'QR Code Deleted'), ('USER_UPDATED', 'User Updated'), ('PERMISSION_CHANGED', 'Permission Changed'), ('User_DESACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated')], max_length=150)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
