# Generated by Django 5.2.1 on 2025-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0002_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('QR_CREATED', 'QR Code Created'), ('QR_UPDATED', 'QR Code Updated'), ('QR_DELETED', 'QR Code Deleted'), ('PERMISSION_CHANGED', 'Permission Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('USER_UPDATED', 'User Updated'), ('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted')], max_length=150),
        ),
    ]
