# Generated by Django 5.2.1 on 2025-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0003_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('QR_CREATED', 'QR Code crée'), ('QR_UPDATED', 'QR Code mis à jour'), ('QR_DELETED', 'QR Code effacé'), ('PERMISSION_CHANGED', 'Permission changée'), ('USER_DEACTIVATED', 'User désactivé'), ('USER_REACTIVATED', 'User réactivé'), ('USER_UPDATED', 'User mis à jour'), ('USER_CREATED', 'User créé'), ('USER_DELETED', 'User supprimé')], max_length=150),
        ),
    ]
