# Generated by Django 5.2.1 on 2025-05-28 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0004_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCleanupTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cleanup', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
