# Generated by Django 5.2.1 on 2025-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0005_logcleanuptracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
    ]
