# Generated by Django 5.2.1 on 2025-06-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_scan_geo_data_scan_geo_city_scan_geo_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='geo_ip',
        ),
    ]
